# Thanos Receive Secret for Object Store (objstore.yml)
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore
  namespace: thanos
type: Opaque
stringData:
  objstore.yml: |
    type: s3
    config:
      bucket: thanos
      endpoint: minio.thanos.svc.cluster.local:9000
      access_key: minioadmin
      secret_key: minioadmin
      insecure: true
---
# Thanos Receive Hashrings Secret
apiVersion: v1
kind: Secret
metadata:
  name: thanos-receive-hashrings
  namespace: thanos
type: Opaque
stringData:
  hashrings.json: |
    [
      {
        "endpoints": [
          "thanos-receive.thanos.svc.cluster.local:10901"
        ]
      }
    ]
---