apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: admin
  labels:
    strimzi.io/cluster: telemetry
  namespace: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations: ['All']
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations: ['All']
      - resource:
          type: cluster
          name: '*'
          patternType: literal
        operations: ['All']
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operations: ['All']
