mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
    # nodePort: 30317
    appProtocol: grpc
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    enabled: false
    


config:
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133
      
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    
    prometheus:
      config:
        scrape_configs:
          - job_name: 'kubernetes-pods'
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              # Only scrape pods with this annotation
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true

              # Use the port specified in the annotation `prometheus.io/port`
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
                action: replace
                target_label: __address__
                regex: (.+)
                replacement: $1
                separator: ':'

              # Use the path specified in the annotation `prometheus.io/path`
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
                replacement: $1

              # Optional: drop pods that don't have the scrape annotation at all
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: drop
                regex: ""

  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 400
      spike_limit_mib: 100
    batch:
      send_batch_max_size: 10000
      timeout: 0s

  exporters:
    kafka/traces:
      brokers: ["telemetry-kafka-bootstrap.kafka:9093"]
      topic: otel-traces
      encoding: otlp_json
      # protocol_version: "2.8.0"
      auth:
        sasl:
          mechanism: SCRAM-SHA-512
          username: traces-producer
          password: ${TRACES_PRODUCER_KAFKA_PASSWORD}
        tls:
          insecure_skip_verify: true

    kafka/metrics:
      brokers: ["telemetry-kafka-bootstrap.kafka:9093"]
      topic: prometheus-metrics
      encoding: otlp_json
      # protocol_version: "2.8.0"
      auth:
        sasl:
          mechanism: SCRAM-SHA-512
          username: metrics-producer
          password: ${METRICS_PRODUCER_KAFKA_PASSWORD}
        tls:
          insecure_skip_verify: true

    kafka/logs:
      brokers: ["telemetry-kafka-bootstrap.kafka:9093"]
      topic: logs
      encoding: otlp_json
      # protocol_version: "2.8.0"
      auth:
        sasl:
          mechanism: SCRAM-SHA-512
          username: logs-producer
          password: ${LOGS_PRODUCER_KAFKA_PASSWORD}
        tls:
          insecure_skip_verify: true

  service:
    extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [kafka/traces]

      metrics:
        receivers: [prometheus]
        processors: [memory_limiter, batch]
        exporters: [kafka/metrics]

      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [kafka/logs]

extraEnvs:
  - name: TRACES_PRODUCER_KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: traces-producer
        key: password
  - name: METRICS_PRODUCER_KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: metrics-producer
        key: password
  - name: LOGS_PRODUCER_KAFKA_PASSWORD
    valueFrom:
      secretKeyRef:
        name: logs-producer
        key: password

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi