apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-k8s-binding
subjects:
  - kind: ServiceAccount
    name: otel-gateway-opentelemetry-collector
    namespace: otel-gateway
roleRef:
  kind: ClusterRole
  name: otel-collector-k8s-access
  apiGroup: rbac.authorization.k8s.io
