mode: "deployment"

image:
  repository: otel/opentelemetry-collector-contrib

fullnameOverride: telemetry-edge-gateway

ports:
  otlp:
    enabled: true
  otlp-http:
    enabled: true
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    enabled: false

config:
  receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: 'kubernetes-pods'
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              # Only scrape pods with this annotation
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true

              # Use the port specified in the annotation `prometheus.io/port`
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
                action: replace
                target_label: __address__
                regex: (.+)
                replacement: $1
                separator: ':'

              # Use the path specified in the annotation `prometheus.io/path`
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
                replacement: $1

              # Optional: drop pods that don't have the scrape annotation at all
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: drop
                regex: ""
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
          tls:
            cert_file: /certs/tls.crt
            key_file: /certs/tls.key
            ca_file: /certs/ca.crt
        http:
          endpoint: 0.0.0.0:4318
          tls:
            cert_file: /certs/tls.crt
            key_file: /certs/tls.key
            ca_file: /certs/ca.crt

  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 400
      spike_limit_mib: 100
    batch:
      send_batch_max_size: 10000
      timeout: 0s

  exporters:
    otlp:
      endpoint: telemetry-gateway.telemetry-gateway:4317
      tls:
        ca_file: /certs/ca.crt
        cert_file: /certs/tls.crt
        key_file: /certs/tls.key

  service:
    pipelines:
      metrics:
        receivers: [prometheus]
        processors: [memory_limiter, batch]
        exporters: [otlp]

      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlp]

      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlp]

extraVolumes:
  - name: certs
    secret:
      secretName: telemetry-edge-tls-secret

extraVolumeMounts:
  - name: certs
    mountPath: /certs
    readOnly: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
