apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: otel-traces
  labels:
    strimzi.io/cluster: telemetry
  namespace: kafka
spec:
  partitions: 1
  replicas: 1

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: prometheus-metrics
  labels:
    strimzi.io/cluster: telemetry
  namespace: kafka
spec:
  partitions: 1
  replicas: 1

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: logs
  labels:
    strimzi.io/cluster: telemetry
  namespace: kafka
spec:
  partitions: 1
  replicas: 1
